<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trial Balance - {{ $business->business_name ?? 'StoreBook' }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    @include('partials.standalone-report-styles')
</head>
<body>

<div class="page-container">

    <div class="filters no-print">
        <form action="{{ route('trial-balance.index') }}" method="GET" class="filter-form">
            <div class="form-group">
                <label for="as_of_date">As of Date</label>
                <input type="date" id="as_of_date" name="as_of_date" value="{{ $asOfDate }}" required>
            </div>
            <div class="form-group">
                <label for="basis">Accounting Basis</label>
                <select id="basis" name="basis" required>
                    <option value="accrual" {{ $basis === 'accrual' ? 'selected' : '' }}>Accrual</option>
                    <option value="cash" {{ $basis === 'cash' ? 'selected' : '' }}>Cash</option>
                </select>
            </div>
            <div class="button-group">
                <button type="submit" class="btn-primary">Search</button>
                <button type="button" class="btn-print" onclick="window.print()">Print</button>
                <a href="{{ route('finance.index') }}" class="btn-secondary btn-link">Back</a>
            </div>
        </form>
    </div>

    <x-report-header :business="$business" title="Trial Balance">
        <div><strong>Basis:</strong> {{ ucfirst($basis) }}</div>
        <div><strong>As of:</strong> <span class="meta-pill">@businessDate($asOfDate)</span></div>
    </x-report-header>

    @if($basis === 'cash' && !empty($trialBalanceData['excluded_accounts']))
        <div class="notice-box no-print">
            <h4>Cash Basis Notice</h4>
            <p>The following accounts are excluded in cash basis accounting:</p>
            <ul>
                @foreach($trialBalanceData['excluded_accounts'] as $excludedAccount)
                    <li>{{ $excludedAccount }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="table-container">
        <table class="report-table">
            <thead>
                <tr>
                    <th>Account</th>
                    <th class="amount">Net Debit</th>
                    <th class="amount">Net Credit</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $currentType = null;
                    $typeLabels = [
                        'asset' => 'Assets',
                        'liability' => 'Liabilities',
                        'equity' => 'Equities',
                        'income' => 'Income',
                        'expense' => 'Expense',
                    ];
                @endphp
                @forelse($trialBalanceData['accounts'] as $account)
                    @if($currentType !== $account['type'])
                        @php $currentType = $account['type']; @endphp
                        <tr class="category-row">
                            <td colspan="3">{{ $typeLabels[$account['type']] ?? ucfirst($account['type']) }}</td>
                        </tr>
                    @endif
                    <tr>
                        <td class="sub-row">
                            <a href="{{ route('general-ledger.index', ['account_id' => $account['id'], 'as_of_date' => $asOfDate, 'basis' => $basis]) }}" class="account-link">
                                {{ $account['name'] }}
                            </a>
                        </td>
                        <td class="amount">{{ $account['debit'] > 0 ? number_format($account['debit'], 2) : '—' }}</td>
                        <td class="amount">{{ $account['credit'] > 0 ? number_format($account['credit'], 2) : '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="3" class="empty-state">No accounts found.</td></tr>
                @endforelse
            </tbody>
            @if(!empty($trialBalanceData['accounts']))
                <tfoot>
                    <tr class="total-row">
                        <td><strong>Total for Trial Balance</strong></td>
                        <td class="amount"><strong class="debit-val">{{ number_format($trialBalanceData['totals']['debit'], 2) }}</strong></td>
                        <td class="amount"><strong class="credit-val">{{ number_format($trialBalanceData['totals']['credit'], 2) }}</strong></td>
                    </tr>
                </tfoot>
            @endif
        </table>
    </div>

    <div class="report-footer">
        <span>Generated by: {{ auth()->user()->name ?? 'User' }}</span>
        <span>Printed: @businessDateTime(now())</span>
    </div>

</div>

</body>
</html>
